package com.modeunsa.global.aop.saga;

public enum OrderSagaStep {

  // ORDER
  ORDER_CREATE_START,
  ORDER_CREATE_COMPLETE,
  ORDER_CREATE_FAILED,

  // PAYMENT
  PAYMENT_IN_PROGRESS,
  PAYMENT_SUCCESS,
  PAYMENT_FINAL_FAILED,

  // REFUND
  ORDER_REFUND_REQUEST,
  PAYMENT_REFUND_COMPLETE,
  PAYMENT_REFUND_FAILED,
  ORDER_REFUND_COMPLETE,

  // INVENTORY
  INVENTORY_RESERVE,
  INVENTORY_RELEASE
}
