package com.modeunsa.global.aop.saga;

public enum OrderSagaStep {

  // ORDER
  ORDER_CREATE_START,
  ORDER_CREATE_COMPLETE,
  ORDER_CREATE_FAILED,

  // PAYMENT
  PAYMENT_PENDING,
  PAYMENT_IN_PROGRESS,
  PAYMENT_IN_PROGRESS_FOR_PG,
  PAYMENT_PG_CONFIRM,
  PAYMENT_FAILED,
  PAYMENT_SUCCESS,
  PAYMENT_FINAL_FAILED,

  // REFUND
  ORDER_REFUND_REQUEST,
  PAYMENT_REFUND_REQUEST,
  PAYMENT_REFUND_SUCCESS,
  ORDER_REFUND_SUCCESS,
  ORDER_REFUND_FAILED,

  // INVENTORY
  INVENTORY_RESERVE,
  INVENTORY_RELEASE
}
